# Generated by Django 4.1.5 on 2023-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('login_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(default=0, max_length=20, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('display_picture', models.ImageField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=30)),
                ('active_status', models.BooleanField(default=True)),
                ('roll', models.CharField(default='student', max_length=15)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
