# Generated by Django 4.1.5 on 2023-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_number',
            field=models.CharField(default=0, max_length=20, null=True, unique=True),
        ),
    ]
