# Generated by Django 4.1.5 on 2023-01-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_person_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
