# Generated by Django 4.1.5 on 2023-01-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_name_person_first_name_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='login_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
