# Generated by Django 4.1.5 on 2023-01-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_person_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_number',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
