# Generated by Django 4.1.5 on 2023-01-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_person_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='password_hash',
        ),
    ]
