# Generated by Django 4.1.5 on 2023-01-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Modules',
            fields=[
                ('module_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('module_num', models.PositiveSmallIntegerField(null=True)),
                ('module_name', models.CharField(max_length=30)),
                ('module_type', models.CharField(default=' Content ', max_length=30)),
                ('Description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('progress', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'Course_Modules',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('course_description', models.CharField(max_length=500)),
                ('display_picture', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.TimeField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_modules')),
            ],
            options={
                'db_table': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('question_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_modules')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tests')),
            ],
            options={
                'db_table': 'Question_Bank',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.PositiveSmallIntegerField(default=1)),
                ('marks_deducted', models.PositiveSmallIntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question_bank')),
            ],
            options={
                'db_table': 'Options',
            },
        ),
        migrations.AddField(
            model_name='course_modules',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
