# Generated by Django 4.1.5 on 2023-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guide',
            table='Guide',
        ),
    ]
